#!/usr/bin/env python3
"""
Packs WRITE-OFF into a single self extracting Lua file.

For when there is nowhere to host the files. One pastebin instead of sixteen,
and running it writes the whole folder back out so the modules stay editable.

    python3 tools/bundle.py                     -> writeoff-bundle.lua
    python3 tools/bundle.py --strip             -> smaller, comments removed
    python3 tools/bundle.py --out somewhere.lua
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FILES = ["writeoff.lua"] + [
    "lib/" + n for n in [
        "util.lua", "ui.lua", "data.lua", "tiles.lua", "body.lua", "fall.lua",
        "inv.lua", "mapgen.lua", "phys.lua", "render.lua", "combat.lua",
        "run.lua", "screens.lua", "save.lua",
    ]
]


def pick_delimiter(bodies):
    """Find a long string level that appears in none of the files."""
    for level in range(1, 12):
        eq = "=" * level
        close = "]" + eq + "]"
        open_ = "[" + eq + "["
        if not any(close in b or open_ in b for b in bodies):
            return eq
    raise SystemExit("every long string delimiter is taken, which should be impossible")


def strip_lua(src):
    """Drop full line comments and blank lines. Leaves string literals alone by
    only touching lines whose first non space character starts a comment."""
    out = []
    in_long = False
    for line in src.split("\n"):
        stripped = line.strip()
        if in_long:
            if "]]" in stripped:
                in_long = False
            continue
        if stripped.startswith("--[["):
            if "]]" not in stripped:
                in_long = True
            continue
        if stripped.startswith("--"):
            continue
        if stripped == "":
            continue
        out.append(line)
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "writeoff-bundle.lua"))
    ap.add_argument("--strip", action="store_true",
                    help="remove comments and blank lines to shrink the paste")
    args = ap.parse_args()

    bodies, missing = {}, []
    for path in FILES:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            missing.append(path)
            continue
        src = open(full, encoding="utf-8").read()
        if args.strip:
            src = strip_lua(src)
        bodies[path] = src
    if missing:
        raise SystemExit("missing: " + ", ".join(missing))

    eq = pick_delimiter(list(bodies.values()))
    open_, close = "[" + eq + "[", "]" + eq + "]"

    parts = [
        "-- WRITE-OFF, packed into one file.",
        "--",
        "-- Run this once and it writes the game out to /writeoff, then offers to",
        "-- play. Your ledger and any saved run in /writeoff-data are left alone.",
        "--",
        "-- Generated by tools/bundle.py. Do not edit this file; edit the modules",
        "-- it was built from and run the bundler again.",
        "",
        'local DEST = "/writeoff"',
        "local FILES = {}",
        "local ORDER = {}",
        "",
        "local function put(path, body)",
        "  FILES[path] = body",
        "  ORDER[#ORDER + 1] = path",
        "end",
        "",
    ]

    for path in FILES:
        body = bodies[path]
        # a long string swallows a leading newline, so add one deliberately
        parts.append('put("%s", %s\n%s%s)' % (path, open_, body, close))
        parts.append("")

    parts.append(r'''
local function colour(c)
  if term.isColour and term.isColour() then term.setTextColour(c) end
end

local function writeFile(path, body)
  local dir = fs.getDir(path)
  if dir ~= "" and not fs.exists(dir) then fs.makeDir(dir) end
  local f = fs.open(path, "w")
  if not f then return false end
  f.write(body)
  f.close()
  return true
end

colour(colours.yellow)
print("WRITE-OFF")
colour(colours.lightGrey)
print("unpacking " .. #ORDER .. " files to " .. DEST)
colour(colours.white)
print("")

local wrote, failed = 0, 0
for _, path in ipairs(ORDER) do
  if writeFile(DEST .. "/" .. path, FILES[path]) then
    wrote = wrote + 1
  else
    failed = failed + 1
    colour(colours.red)
    print("  could not write " .. path)
    colour(colours.white)
  end
end

if failed > 0 then
  colour(colours.red)
  print(failed .. " files failed. Check the disk has room.")
  colour(colours.white)
  return
end

colour(colours.lime)
print("Wrote " .. wrote .. " files.")
colour(colours.white)
if fs.exists("/writeoff-data") then
  colour(colours.lightGrey)
  print("Your ledger and saved run were left alone.")
  colour(colours.white)
end
print("")
print("Run it with:  " .. DEST .. "/writeoff")

if shell then
  print("")
  write("Play now? (y/n) ")
  while true do
    local _, key = os.pullEvent("char")
    if key == "y" or key == "Y" then
      print("")
      shell.run(DEST .. "/writeoff")
      return
    elseif key == "n" or key == "N" then
      print("")
      return
    end
  end
end
'''.lstrip("\n"))

    out = "\n".join(parts)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(out)

    kb = len(out.encode("utf-8")) / 1024
    print("wrote %s  (%d files, %.0f KB)" % (args.out, len(FILES), kb))
    if kb > 480:
        print("warning: over 480 KB, which is close to the pastebin limit."
              " try --strip")


if __name__ == "__main__":
    main()
